### ISSUE TITLE
Better Example App

### ISSUE THREAD

**Issue by tomassliz** [Cleverlance/Pyramid#11]
It will be nice to have some simple app like _todo list_ or _twitter app_ as the example. Currently the example contains only some tests and therefore it is not clear how to apply this architecture in the real life development.

I would like to help with this. Is it now feasible? Or is the development of core parts still in progress? Feel free to contact me directly.

**Comment by jakubvano** [comment]
@tomassliz agreed, it would be useful to have better usage demonstration. 

This code was basically exported from couple of projects I have worked on, but until recently I've not used this as a pod in any real project. Few weeks ago I've started a new work project, integrated Pyramid and deal with bugs / improvement as I go.

Version `0.4.0` should have core features finalized and debugged - However, I probably wont be able to find time to write some example app / proper documentation any time soon. If you are up for it, I would welcome any contribution 😉 

PS: Sorry for late response, I've been neglecting my github notifications in past months 😞...
